{% set name = "spotiflow" %}
{% set version = "0.5.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spotiflow-{{ version }}.tar.gz
  sha256: 2d58040491e53f8778c47c18172265d4a7aae96ae762a9d30b5bfafe49354472

build:
  skip: true  # [win or py<310 or py>=313]
  entry_points:
    - spotiflow-predict = spotiflow.cli.predict:main
    - spotiflow-train = spotiflow.cli.train:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - setuptools >=40.8.0
    - setuptools-scm >=6.2
    - wheel
    - numpy
    - pip
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  run:
    - python
    - configargparse
    - crick
    - csbdeep
    - dask
    - lightning
    - importlib-metadata >=4.4  # [py<312]
    - networkx
    - pandas
    - pillow
    - pydash
    - scikit-image
    - scipy
    - setuptools
    - tensorboard
    - tifffile
    - torchvision
    - tqdm
    - typing-extensions
    - wandb
    - zarr

test:
  imports:
    - spotiflow
  commands:
    - pip check
    - spotiflow-predict --help
  requires:
    - pip

about:
  home: https://github.com/weigertlab/spotiflow
  summary: Spotiflow - accurate and efficient spot detection for microscopy data
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - spotiflow/lib/external/nanoflann/LICENSE.txt

extra:
  recipe-maintainers:
    - AlbertDominguez
